name: "Validation And Formatting"
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Download repo
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        name: Setup Python
      - uses: hacs/action@main
        name: HACS Validation
        with:
          CATEGORY: integration
          ignore: wheels
      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master" 
      - run: |
          python3 -m pip install black
          black custom_components --check
        name: Format validation
